# Generated by Django 4.1.7 on 2023-03-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recettes',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='recettes',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='recettes',
            old_name='taste',
            new_name='tastes',
        ),
    ]
