# Generated by Django 4.1.7 on 2023-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='sous_vide_pression',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='recette',
            name='sous_vide_soudure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temperature',
            field=models.IntegerField(blank=True),
        ),
    ]
