# Generated by Django 4.1.7 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='allergenes',
            field=models.ManyToManyField(to='core_routes.allergenes'),
        ),
    ]
