# Generated by Django 4.1.7 on 2023-06-05 16:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0002_alter_fournisseur_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseurback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 5), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 5), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitpricetracker',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 5), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 5), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
