# Generated by Django 4.1.7 on 2023-03-14 17:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0002_ingredients_allergenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('personne', 'Personne'), ('gramme', 'Gramme'), ('kilorgamme', 'Kilogramme'), ('littre', 'Littre'), ('centilittre', 'Centilittre')], default='personne', max_length=100)),
                ('duration', models.IntegerField()),
                ('last_modification', models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 14), message='Date can not be later than today')])),
                ('selected_for_menu', models.BooleanField(default=False)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RecettesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecettesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecettesInsipirations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecettesTastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='conversion_to_kilo',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('gramme', 'Gramme'), ('kilogramme', 'Kilogramme'), ('centilittre', 'Centilittre'), ('littre', 'Littre'), ('unité', 'Unite'), ('table_spoon', 'Cuillere A Soupe'), ('teas_spoon', 'Cuillere A Cafe'), ('cup', 'Cup')], default='kilogramme', max_length=100),
        ),
        migrations.CreateModel(
            name='RecettesPogressionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('text', models.TextField()),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_routes.recettes')),
            ],
        ),
        migrations.CreateModel(
            name='RecettesIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('gramme', 'Gramme'), ('kilogramme', 'Kilogramme'), ('centilittre', 'Centilittre'), ('littre', 'Littre'), ('unité', 'Unite'), ('table_spoon', 'Cuillere A Soupe'), ('teas_spoon', 'Cuillere A Cafe'), ('cup', 'Cup')], default='kilogramme', max_length=100)),
                ('quantity_in_kilogramme', models.DecimalField(decimal_places=7, default=1, max_digits=12)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_routes.ingredients')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_routes.recettes')),
            ],
        ),
        migrations.AddField(
            model_name='recettes',
            name='category',
            field=models.ManyToManyField(to='core_routes.recettescategories'),
        ),
        migrations.AddField(
            model_name='recettes',
            name='genre',
            field=models.ManyToManyField(to='core_routes.recettesgenres'),
        ),
        migrations.AddField(
            model_name='recettes',
            name='taste',
            field=models.ManyToManyField(to='core_routes.recettestastes'),
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('gramme', 'Gramme'), ('kilogramme', 'Kilogramme'), ('centilittre', 'Centilittre'), ('littre', 'Littre'), ('unité', 'Unite'), ('table_spoon', 'Cuillere A Soupe'), ('teas_spoon', 'Cuillere A Cafe'), ('cup', 'Cup')], default='kilogramme', max_length=100)),
                ('conversion_to_kilo', models.DecimalField(decimal_places=7, default=1, max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_routes.ingredients')),
            ],
        ),
    ]
