# Generated by Django 4.1.7 on 2023-03-30 17:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0002_rename_category_recettes_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='recettes',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='recettesingredients',
            name='quantity_in_kilogramme',
        ),
        migrations.AlterField(
            model_name='recettes',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 30), message='Date can not be later than today')]),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_routes.ingredientscategories'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='sub_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_routes.ingredientssubcategories'),
        ),
    ]
