# Generated by Django 4.1.7 on 2023-04-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0002_alter_recette_sous_vide_pression_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='categories',
            new_name='category',
        ),
    ]
