# Generated by Django 4.1.7 on 2023-03-30 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0003_ingredientscategories_ingredientssubcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='allergenes',
            field=models.ManyToManyField(blank=True, to='core_routes.allergenes'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_routes.ingredientscategories'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='conversion_to_kilo',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='labels',
            field=models.ManyToManyField(blank=True, to='core_routes.labels'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='sub_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_routes.ingredientssubcategories'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, default='kilogramme', max_length=100),
        ),
    ]
