# Generated by Django 4.1.7 on 2023-06-07 19:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0003_alter_fournisseurback_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='last_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseurback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 7), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 7), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitpricetracker',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 7), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 6, 7), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sousrecette',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
