# Generated by Django 4.1.7 on 2023-03-17 00:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0003_recettes_recettescategories_recettesgenres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversions',
            name='conversion_to_kilo',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name='conversions',
            name='unit',
            field=models.CharField(default='kilogramme', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='illustration',
            field=models.FileField(blank=True, upload_to='ingredients/'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(default='kilogramme', max_length=100),
        ),
        migrations.AlterField(
            model_name='recettes',
            name='last_modification',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 17), message='Date can not be later than today')]),
        ),
    ]
