# Generated by Django 4.1.7 on 2023-04-24 13:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0003_rename_categories_recette_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 4, 24), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='season_end',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recette',
            name='season_start',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], max_length=100),
        ),
    ]
