# Generated by Django 4.1.7 on 2023-07-08 15:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0003_alter_avoir_date_created_alter_avoir_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='latest_kilogramme_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='date_created',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='date_received',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='date_created',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_created',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='expected_delivery_date',
            field=models.DateField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='fournisseurback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitback',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='produitpricetracker',
            name='created_on',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 7, 8), message='Date can not be later than today')]),
        ),
    ]
