# Generated by Django 4.1.7 on 2023-03-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0004_alter_ingredients_allergenes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecettesPogressionElements',
            new_name='RecettesProgressionElements',
        ),
    ]
