# Generated by Django 4.1.7 on 2023-04-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0004_alter_recette_last_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteingredient',
            name='section',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='unit',
            field=models.CharField(default='kilogramme', max_length=100),
        ),
    ]
