# Generated by Django 4.1.7 on 2023-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0005_rename_recettespogressionelements_recettesprogressionelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousrecettes',
            name='quantity',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=12),
        ),
    ]
