# Generated by Django 4.1.7 on 2023-04-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0005_alter_recetteingredient_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteingredient',
            name='section',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
