# Generated by Django 4.1.7 on 2023-04-24 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0006_alter_recetteingredient_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteprogressionelement',
            name='section',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
