# Generated by Django 4.1.7 on 2023-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0006_alter_recette_last_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='last_evolution',
            field=models.CharField(choices=[('HIGHER', 'Higher'), ('LOWER', 'Lower'), ('STILL', 'Still'), ('SAME', 'Same')], default='FIRST', max_length=100),
        ),
    ]
