# Generated by Django 4.1.7 on 2023-06-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0007_recette_last_evolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='last_evolution',
        ),
    ]
