# Generated by Django 4.1.7 on 2023-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0008_alter_recetteprogressionelement_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousrecette',
            name='quantity_in_kilogramme',
        ),
        migrations.AddField(
            model_name='sousrecette',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
