# Generated by Django 4.1.7 on 2023-04-26 15:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0010_alter_sousrecette_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 4, 26), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=7, max_digits=12),
        ),
    ]
