# Generated by Django 4.1.7 on 2023-04-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0011_alter_recette_last_modification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_routes.recettecategory'),
        ),
    ]
