# Generated by Django 4.1.7 on 2023-04-26 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0014_alter_recette_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='season_end',
            field=models.CharField(blank=True, choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='season_start',
            field=models.CharField(blank=True, choices=[('Janvier', 'Janvier'), ('Février', 'Fevrier'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Aout'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Decembre')], max_length=100, null=True),
        ),
    ]
