# Generated by Django 4.1.7 on 2023-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0015_alter_recette_duration_alter_recette_season_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='sous_vide_pression',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='sous_vide_soudure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='unit',
            field=models.CharField(choices=[('personne', 'Personne'), ('gramme', 'Gramme'), ('kilorgamme', 'Kilogramme'), ('littre', 'Littre'), ('centilittre', 'Centilittre')], default='personne', max_length=100, null=True),
        ),
    ]
