# Generated by Django 4.1.7 on 2023-04-26 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0016_alter_recette_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='is_to_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='tva',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MaxValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='unit',
            field=models.CharField(choices=[('personne', 'Personne'), ('gramme', 'Gramme'), ('kilorgamme', 'Kilogramme'), ('littre', 'Littre'), ('centilittre', 'Centilittre')], max_length=100, null=True),
        ),
    ]
