# Generated by Django 4.1.7 on 2023-04-29 12:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_routes', '0017_alter_recette_is_to_modify_alter_recette_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_april',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_august',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_december',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_february',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_january',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_july',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_june',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_march',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_may',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_november',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_october',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='is_in_season_september',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recette',
            name='last_modification',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 4, 29), message='Date can not be later than today')]),
        ),
        migrations.AlterField(
            model_name='recette',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sousrecette',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='sousrecette',
            constraint=models.CheckConstraint(check=models.Q(('recette', models.F('sous_recette')), _negated=True), name='can_not_add_itself'),
        ),
    ]
